language: python
python:
    - 2.7
    - 3.6
os: linux
sudo: required
dist: trusty

env:
  matrix:
     - CONAN_COMPILER=gcc CONAN_COMPILER_VERSION=4.8

matrix:
   include:
       - os: osx 
         osx_image: xcode8.3 # apple-clang 8.1
         language: generic 
      

install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh

script:
  - chmod +x .travis/run.sh
  - ./.travis/run.sh